on:
  push:
    branches:
      - 'main'
  delete:
    branches:
      - 'feature**'
jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run ${{ secrets.POSTMAN_API_COLLETION }}
  build-deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: build function
        run: |
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          export SAM_CLI_TELEMETRY=0
          sam validate
          sam build
          sam deploy --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset
